#!/usr/bin/python

import Pashua
from flickrapi import FlickrAPI
import sys, os
import subprocess
import re

# Local parameters
extension = "jpg"
localdir = os.environ['HOME'] + "/Desktop"
tempfile = "temp.jpg"

# Flickr parameters
fuser = 'your Flickr username'
key = 'get your key from Flickr'
secret = 'get your secret from Flickr'
screenshotsID = 'the ID of the Flickr set'

# Dialog box configuration
conf = '''
# Window properties
*.title = Snapshot Flickr

# File name text field properties
fn.type = textfield
fn.default = snap
fn.width = 264
fn.x = 94
fn.y = 130
fnl.type = text
fnl.default = File name:
fnl.x = 20
fnl.y = 132

# Description text field properties
desc.type = textbox
desc.width = 264
desc.height = 72
desc.x = 94
desc.y = 40
descl.type = text
descl.default = Description:
descl.x = 10
descl.y = 95


# Local files checkbox properties
lf.type = checkbox
lf.label = Local file only
lf.x = 20
lf.y = 5

# Default button
db.type = defaultbutton
db.label = Save

# Cancel button
cb.type = cancelbutton
'''

# Go to the localdir.
os.chdir(localdir)

# Capture a portion of the screen and save it to a temporary file.
subprocess.call(["screencapture", "-iW", "-t", extension, tempfile])

# Exit if the user canceled the screencapture.
if not os.access(tempfile, os.F_OK):
  sys.exit()

# Open the dialog box and get the input.
dialog = Pashua.run(conf)
if dialog['cb'] == '1':
  os.remove(tempfile)
  sys.exit()

# Rename the temporary file.
fn =  '%s.%s' % (dialog['fn'], extension)
subprocess.call(["mv", tempfile, fn])

# Unless this is just a local file...
if dialog['lf'] != '1':
  
  # Upload the file.
  flickr = FlickrAPI(api_key=key, secret=secret)
  response = flickr.upload(filename=fn, title=dialog['fn'],\
              description=dialog['desc'], is_public=1,\
              format='etree')
  
  # Get the photo info from Flickr.
  photoID = response.find('photoid').text
  photoURL = 'http://www.flickr.com/photos/%s/%s/' % (fuser, photoID)
  
  # Add to the screenshots set.
  flickr.photosets_addPhoto(photo_id = photoID, photoset_id = screenshotsID)
  
  # Open the photo page in the default browser.
  subprocess.call(['open', photoURL])
  
  # Put an img element on the clipboard for the Medium 640 size of the image.
  flickr = FlickrAPI(api_key=key, secret=secret)
  etree = flickr.photos_getSizes(photo_id = photoID, format = 'etree')
  for i in etree[0]:
    if i.attrib['label'] == 'Medium 640':
      tag = '<img src="%s" alt="%s" title="%s" />' %\
        (i.attrib['source'], dialog['fn'], dialog['fn'])
      subprocess.Popen('pbcopy', stdin=subprocess.PIPE).communicate(tag)
      sys.exit()
  
  # If the Medium 640 size wasn't available.
  tag = '<img src="%s" alt="%s" title="%s" />' %\
    ('size_not_found', dialog['fn'], dialog['fn'])
  subprocess.Popen('pbcopy', stdin=subprocess.PIPE).communicate(tag)
  